name: List Files in Repository  
on: 
  push:
    branches:
      - main
jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files
      run: |
        echo "Listing files in the repository:"
        ls -al
